image: drewcarlson/docker-android

variables:
  SIGNING_KEY: /builds/breadwallet/breadwallet-android/FakeSigningKey
  SIGNING_PASSWORD: qwerty
  SIGNING_ALIAS: key0
  SIGNING_ALIAS_PASSWORD: qwerty

cache:
  key: ${CI_PROJECT_ID}-2
  paths:
    - ~/.gradle/
    - /root/.gradle/

detekt:
  stage: test
  script:
    - ./gradlew --console=plain detekt
  only:
    - merge_requests
  artifacts:
    expose_as: "Detekt Report"
    paths:
      - app/build/reports/detekt/detekt.html

debug:test:
  stage: test
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew --console=plain assembleDebug testBrdDebugUnitTest testBrdTestnetDebugUnitTest
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - app/build/outputs/apk/brd/debug/
      - app/build/outputs/apk/brdTestnet/debug/
    reports:
      junit: app/build/test-results/**/TEST-*.xml

deploy-appetize:
  stage: deploy
  needs: ["debug:test"]
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - fastlane appetizeUpload flavor:brd
    - fastlane appetizeUpload flavor:brdTestnet
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: $NATIVE_REVIEW_URL?versionName=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    on_stop: stop-review

stop-review:
  stage: deploy
  needs: ["debug:test"]
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - cd $CI_PROJECT_DIR; fastlane appetizeRemove flavor:brd merge:$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - cd $CI_PROJECT_DIR; fastlane appetizeRemove flavor:brdTestnet merge:$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  when: manual
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    action: stop

release:test:
  stage: test
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew --console=plain testBrdReleaseUnitTest testBrdTestnetReleaseUnitTest
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    reports:
      junit: app/build/test-results/**/TEST-*.xml

release:deploy-firebase:
  stage: deploy
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew --console=plain assembleRelease appDistributionUploadBrdRelease appDistributionUploadBrdTestnetRelease
  rules:
    - if: '$CI_COMMIT_TAG != null'
  artifacts:
    paths:
      - app/build/outputs/apk/brd/release/
      - app/build/outputs/apk/brdTestnet/release/

debug:deploy-firebase:
  stage: deploy
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew --console=plain assembleDebug appDistributionUploadBrdDebug appDistributionUploadBrdTestnetDebug
  rules:
    - if: '$CI_COMMIT_TAG != null'
  artifacts:
    paths:
      - app/build/outputs/apk/brd/debug/
      - app/build/outputs/apk/brdTestnet/debug/
