image: alvrme/alpine-android:android-29

variables:
  SIGNING_KEY: /builds/breadwallet/breadwallet-android/FakeSigningKey
  SIGNING_PASSWORD: qwerty
  SIGNING_ALIAS: key0
  SIGNING_ALIAS_PASSWORD: qwerty
  ORG_GRADLE_DAEMON: "false"
  ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  ORG_GRADLE_CONSOLE: plain

cache:
  key: ${CI_PROJECT_ID}-3
  paths:
    - ~/.gradle/
    - /root/.gradle/

detekt:
  stage: test
  script:
    - ./gradlew detekt
  only:
    - merge_requests
  artifacts:
    expose_as: "Detekt Report"
    paths:
      - app/build/reports/detekt/detekt.html

debug:test:
  stage: test
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew assembleDebug testBrdDebugUnitTest testBrdTestnetDebugUnitTest
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - app/build/outputs/apk/brd/debug/
      - app/build/outputs/apk/brdTestnet/debug/
    reports:
      junit: app/build/test-results/**/TEST-*.xml

deploy-appetize:
  stage: deploy
  needs: ["debug:test"]
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew appetizeUpload
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: $NATIVE_REVIEW_URL?versionName=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    on_stop: stop-review

stop-review:
  stage: deploy
  needs: ["debug:test"]
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - cd $CI_PROJECT_DIR; ./gradlew appetizeRemove -Pmerge=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  when: manual
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    action: stop

release:test:
  stage: test
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew testBrdReleaseUnitTest testBrdTestnetReleaseUnitTest
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    reports:
      junit: app/build/test-results/**/TEST-*.xml

release:deploy-firebase:
  stage: deploy
  variables:
    ORG_GRADLE_DEPENDENCY_VERIFICATION: "strict"
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew assembleRelease appDistributionUploadBrdRelease appDistributionUploadBrdTestnetRelease
  rules:
    - if: '$CI_COMMIT_TAG != null'
  artifacts:
    paths:
      - app/build/outputs/apk/brd/release/
      - app/build/outputs/apk/brdTestnet/release/

debug:deploy-firebase:
  stage: deploy
  variables:
    ORG_GRADLE_DEPENDENCY_VERIFICATION: "strict"
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew assembleDebug appDistributionUploadBrdDebug appDistributionUploadBrdTestnetDebug
  rules:
    - if: '$CI_COMMIT_TAG != null'
  artifacts:
    paths:
      - app/build/outputs/apk/brd/debug/
      - app/build/outputs/apk/brdTestnet/debug/
