image: circleci/android:api-29

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - /home/circleci/.m2/
    - /home/circleci/.gradle/
    - .gradle/

stages:
  - build

debug:
  stage: build
  script:
    - ./gradlew assembleDebug
    - ./gradlew --console=plain testBrdDebugUnitTest
    - ./gradlew --console=plain detekt
    # - ./gradlew -Pci --console=plain :app:lintBrdDebug -PbuildDir=lint
  only:
    - crypto/prototype
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - app/build/outputs/
      - app/build/test-results
      - app/lint/reports/
      - app/build/reports/detekt

release:
  stage: build
  script:
    - ./gradlew assembleRelease -PIGNORE_FABRIC_KEYS_MISSING
    - ./gradlew --console=plain testBrdReleaseUnitTest
    - ./gradlew --console=plain detekt
    # - ./gradlew -Pci --console=plain :app:lintBrdRelease -PbuildDir=lint
  only:
    - crypto/prototype
    - develop
    - master
    - /^release.*$/
  artifacts:
    paths:
      - app/build/outputs/
      - app/build/test-results
      - app/lint/reports/
      - app/build/reports/detekt
