stages:
  - build
  - deploy

default:
  image: alvrme/alpine-android:android-29-jdk11
  tags:
    - cluster

variables:
  SIGNING_KEY: /builds/breadwallet/brd-mobile/brd-android/FakeSigningKey
  SIGNING_PASSWORD: qwerty
  SIGNING_ALIAS: key0
  SIGNING_ALIAS_PASSWORD: qwerty
  ORG_GRADLE_DAEMON: "false"
  ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  ORG_GRADLE_CONSOLE: plain
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_PROJECT_ID}-3
  paths:
    - ~/.gradle/
    - /root/.gradle/

#detekt:
#  stage: test
#  script:
#    - ./gradlew detekt
#  only:
#    - merge_requests
#  artifacts:
#    expose_as: "Detekt Report"
#    paths:
#      - app/build/reports/detekt/detekt.html

build-android:
  stage: build
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew :brd-android:app:build -xlint -xdetekt --no-daemon
  only:
    - develop
    - main
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - brd-android/app/build/outputs/apk/brd/debug/
      - brd-android/app/build/outputs/apk/brd/release/
      - brd-android/app/build/outputs/apk/brdTestnet/debug/
      - brd-android/app/build/outputs/apk/brdTestnet/release/
    reports:
      junit: ./brd-android/**/build/test-results/**/TEST-*.xml

build-ios:
  stage: build
  script:
    - xcodebuild clean -workspace brd-ios/breadwallet.xcworkspace -scheme breadwallet | xcpretty
    - xcodebuild test -workspace brd-ios/breadwallet.xcworkspace -scheme breadwallet -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.0' | xcpretty -s
  tags:
    - ios-12
    - xcode-10
    - macos-10_13

deploy-appetize:
  stage: deploy
  needs: [ "build-android" ]
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew appetizeUpload
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: $NATIVE_REVIEW_URL?versionName=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    on_stop: stop-review

stop-review:
  stage: deploy
  needs: [ "build-android" ]
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - cd $CI_PROJECT_DIR; ./gradlew appetizeRemove -Pmerge=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  when: manual
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    action: stop

deploy-firebase:
  stage: deploy
  variables:
    ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew assemble appDistributionUploadBrdRelease appDistributionUploadBrdTestnetRelease appDistributionUploadBrdDebug appDistributionUploadBrdTestnetDebug
  rules:
    - if: '$CI_COMMIT_TAG != null'
  artifacts:
    paths:
      - brd-android/app/build/outputs/apk/brd/debug/
      - brd-android/app/build/outputs/apk/brd/release/
      - brd-android/app/build/outputs/apk/brdTestnet/debug/
      - brd-android/app/build/outputs/apk/brdTestnet/release/
